### ISSUE TITLE
Kill-Notice Drawoutline

### ISSUE THREAD

**Issue by wasabilurker** [Stochast1c/solarhud#1]
Heya!

Not directly an issue, but was wondering if its possible to get the red drawoutline on the kill/death notice up in the top right corner and only the red drawout line on kills that I make.

So its easy to know when you've killed someone in game ^^,

(using the dark theme)

Sincerely o/

**Comment by Stochast1c** [comment]
I fairly certain you can't, the only options available to you for your kills (called local in hud files) are font and background colors, but I will try some things out.  At the very least you can change the background color of your kills/deaths very easily by going to HudDeathNotice in scripts/hudlayout.res and changing the LocalBackgroundColor to whatever is easiest to make out.  I think the logical choice would be to invert the color (so use base03).  The only reason why I didn't choose to do that naturally was because every solarized theme I've seen never uses the opposing theme's bg and highlight bg (base2/3).

**Comment by Stochast1c** [comment]
There are no files that control the specific kill/death notice that shows up on screen, so there is no method for me to add a border around any kill/death let alone your specific ones.  

The only way you are going to get more legible notices is by changing the LocalBackgroundColor as mentioned above.  The player font colors will always be team colors so don't pick red or blue as the background color.
