### ISSUE TITLE
Minmode Hud Does not Support Alt Gamemodes besides surf

### ISSUE THREAD

**Issue by ambroon** [Stochast1c/solarhud#4]
http://imgur.com/a/lWz28
When I join into a server, i can only change into these classes.
http://imgur.com/a/lK5gl
The health does not load up either.

**Comment by Stochast1c** [comment]
From the readme:

> Minmode 0 is for the 6s hud and Minmode 1 is for the surfing HUD.

You are currently using minmode 1, which removes all hud elements except the map timer, and only shows the four base move speed classes (since surf mode).

Now for the issue part:

I haven't updated the base move speed classes since I created the hud, and with the spy change, he no longer belongs there.

If you want to use the minmode for bhopping, demo isn't an option.

If you want to use minmode for jumping, you can't select soldier/demo nor can you see your ammo.

I think what I will do is make three categories of classes for the alt modes so you can select them all.  I will also add in customization for enabling/disabling the ammo in minmode.

For the time being, either use minmode and select your class either by pressing the class number (1-scout, 2-soldier, etc.), use the console to select the class (join\_class), or use an existing bind you have created OR just don't use minmode until then.

I'm extremely busy the next bunch of days, but I should have the above done before 2017.

**Comment by ambroon** [comment]
Thank you so much. I will do what you tell me and wait for the new
customization to come out.

**Comment by Stochast1c** [comment]
Most recent commit adds customization for ammo and sticky charge meter as well as removes objective panels and remade the class select panel.
