### ISSUE TITLE
Update Light/Dark

### ISSUE THREAD

**Issue by adamgemmell** [Stochast1c/solarhud#5]
Could you merge master into Light and Dark or archive them and update the tftv thread/readme a bit? spent a bit trying to diagnose stuff on Light thinking it was the release branch and the recent master changes were just you playing around with new stuff

**Comment by Stochast1c** [comment]
Sorry, I'll clean up those branches (archive them and update their readmes) in a bit.   But yes, everything is on the master branch because pushing updates to 4 different branches was getting annoying when I was making constant updates.  

Readme on the master branch is up to date and there are instructions on how to switch themes (default is dark so you will need to switch themes to light).  Let me know if the instructions are unclear.

Going to leave the issue open until I deal with the branches, if something arises after I close this just create a new issue.

**Comment by adamgemmell** [comment]
Np, changing colours is fine for me, I was just using the out of date
branches. Thanks for maintaining it
